drop table if exists category;
drop table if exists brand;
drop table if exists merchandise;

create table category (
    id bigint generated by default as identity,
    name varchar(20),
    primary key (id),
    unique (name)
);

create table brand (
    id bigint generated by default as identity,
    name varchar(20),
    primary key (id)
);

create table merchandise (
    id bigint generated by default as identity,
    category_id bigint,
    brand_id bigint,
    price bigint,
    foreign key (category_id) references category (id),
    foreign key (brand_id) references brand (id)
);